name: demo

on:
  - pull_request
  - workflow_dispatch

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run the action
        uses: ghostdevv/svelte-check-action@main
