name: Tagger

on:
  release:
    types:
      - released
      - edited

jobs:
  actions-tagger:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
     
      - name: Tag Release
        id: action-tagger
        uses: stevenjdh/action-tagger@v1
        with:
          set-latest-tag: true
