name: Keep the versions up-to-date

on:
  workflow_dispatch:
  release:
    types:
      - released
      - edited

jobs:
  actions-tagger:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
     
      - name: Tagger
        uses: Actions-R-Us/actions-tagger@v2
        with:
          publish_latest_tag: true
